on:
    #nosso script será executado sempre quando houver push e pull request nas branches destacadas abaixo
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Sincronizando com o Github
              uses: actions/checkout@v3
            - name: Publicando
              uses: SamKirkland/web-deploy@v1
              with:
                target-server: ${{ secrets.host }}
                remote-user: ubuntu
                private-ssh-key: ${{ secrets.key }}
                destination-path: /home/ubuntu/appdemo1
            - name: Aplicando as mudanças
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.host }}
                username: ubuntu
                key: ${{ secrets.key }}
                port: 22
                script: pm2 restart server
